import type { Lead } from '@/types'

export const seedLeads: Lead[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah@cloudscale.ai',
    phone: '+1 (415) 555-0142',
    company: 'CloudScale AI',
    budget: 25000,
    industry: 'Technology',
    serviceNeeded: 'Full-stack development',
    timeline: 'This week',
    status: 'qualified',
    tags: ['AI', 'Enterprise'],
    notes: 'High priority. Looking for a complete platform rebuild.',
    leadScore: 52,
    source: 'Website',
    createdAt: new Date('2026-07-02'),
    updatedAt: new Date('2026-07-02'),
    userId: 'demo',
  },
  {
    id: '2',
    name: 'Marcus Webb',
    email: 'marcus@luminaweb.com',
    phone: '+1 (212) 555-0198',
    company: 'Lumina Web',
    budget: 8500,
    industry: 'Marketing',
    serviceNeeded: 'Landing page design',
    timeline: 'Next month',
    status: 'new',
    tags: ['SaaS'],
    notes: 'Referred by Sarah Chen.',
    leadScore: 24,
    source: 'Referral',
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    userId: 'demo',
  },
  {
    id: '3',
    name: 'Elena Lopez',
    email: 'elena@aetherdynamics.com',
    phone: '+1 (512) 555-0167',
    company: 'Aether Dynamics',
    budget: 32000,
    industry: 'Technology',
    serviceNeeded: 'Enterprise platform',
    timeline: 'This week',
    status: 'meeting',
    tags: ['Aerospace', 'Tech'],
    notes: 'Meeting scheduled for Thursday.',
    leadScore: 48,
    source: 'Website',
    createdAt: new Date('2026-06-28'),
    updatedAt: new Date('2026-07-03'),
    userId: 'demo',
  },
  {
    id: '4',
    name: 'James Thorne',
    email: 'james@urbanoasis.co',
    phone: '+1 (305) 555-0134',
    company: 'Urban Oasis',
    budget: 4200,
    industry: 'Real Estate',
    serviceNeeded: 'Website redesign',
    timeline: 'Next month',
    status: 'contacted',
    tags: ['Hospitality'],
    notes: 'Follow up next week.',
    leadScore: 18,
    source: 'Social',
    createdAt: new Date('2026-06-20'),
    updatedAt: new Date('2026-06-25'),
    userId: 'demo',
  },
  {
    id: '5',
    name: 'Amira Khan',
    email: 'amira@biogensystems.io',
    phone: '+1 (617) 555-0189',
    company: 'BioGen Systems',
    budget: 15000,
    industry: 'Healthcare',
    serviceNeeded: 'Custom dashboard',
    timeline: 'This week',
    status: 'proposal',
    tags: ['BioTech', 'High-Growth'],
    notes: 'Proposal sent. Awaiting response.',
    leadScore: 38,
    source: 'Referral',
    createdAt: new Date('2026-07-01'),
    updatedAt: new Date('2026-07-03'),
    userId: 'demo',
  },
  {
    id: '6',
    name: 'Daniel Kim',
    email: 'daniel@nexusdigital.dev',
    phone: '+1 (206) 555-0156',
    company: 'Nexus Digital',
    budget: 15000,
    industry: 'Technology',
    serviceNeeded: 'Mobile app development',
    timeline: 'Flexible',
    status: 'qualified',
    tags: ['Agency'],
    notes: 'Needs iOS and Android apps.',
    leadScore: 45,
    source: 'Direct',
    createdAt: new Date('2026-06-25'),
    updatedAt: new Date('2026-07-01'),
    userId: 'demo',
  },
  {
    id: '7',
    name: 'Rachel Adams',
    email: 'rachel@summitco.com',
    phone: '+1 (720) 555-0178',
    company: 'Summit Co',
    budget: 4500,
    industry: 'Real Estate',
    serviceNeeded: 'CRM integration',
    timeline: 'Next month',
    status: 'new',
    tags: ['Real Estate'],
    notes: 'Interested in lead management.',
    leadScore: 22,
    source: 'Website',
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    userId: 'demo',
  },
  {
    id: '8',
    name: 'Tom Baker',
    email: 'tom@corestack.io',
    phone: '+1 (408) 555-0145',
    company: 'CoreStack',
    budget: 35000,
    industry: 'Technology',
    serviceNeeded: 'Full platform build',
    timeline: 'This week',
    status: 'won',
    tags: ['Enterprise', 'Long-term'],
    notes: 'Signed contract. Project kickoff Monday.',
    leadScore: 55,
    source: 'Referral',
    createdAt: new Date('2026-06-15'),
    updatedAt: new Date('2026-07-02'),
    userId: 'demo',
  },
  {
    id: '9',
    name: 'Lisa Park',
    email: 'lisa@greenleafhealth.org',
    phone: '+1 (312) 555-0123',
    company: 'GreenLeaf Health',
    budget: 3200,
    industry: 'Healthcare',
    serviceNeeded: 'Patient portal',
    timeline: 'Flexible',
    status: 'new',
    tags: ['Healthcare'],
    notes: 'Small clinic, tight budget.',
    leadScore: 18,
    source: 'Social',
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    userId: 'demo',
  },
  {
    id: '10',
    name: 'Maya Patel',
    email: 'maya@novatech.co',
    phone: '+1 (512) 555-0199',
    company: 'NovaTech',
    budget: 5500,
    industry: 'Technology',
    serviceNeeded: 'API development',
    timeline: 'This week',
    status: 'new',
    tags: ['SaaS', 'Startup'],
    notes: 'Series A funded. Needs API fast.',
    leadScore: 22,
    source: 'Website',
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    userId: 'demo',
  },
  {
    id: '11',
    name: 'Sofia Ortega',
    email: 'sofia@greenpulse.energy',
    phone: '+1 (503) 555-0167',
    company: 'GreenPulse',
    budget: 6800,
    industry: 'Manufacturing',
    serviceNeeded: 'E-commerce platform',
    timeline: 'Next month',
    status: 'lost',
    tags: ['Renewables'],
    notes: 'Went with a cheaper competitor.',
    leadScore: 22,
    source: 'Direct',
    createdAt: new Date('2026-06-28'),
    updatedAt: new Date('2026-07-02'),
    userId: 'demo',
  },
  {
    id: '12',
    name: 'Robert Blair',
    email: 'robert@heavymetal.com',
    phone: '+1 (313) 555-0144',
    company: 'Heavy Metal Inc.',
    budget: 12000,
    industry: 'Manufacturing',
    serviceNeeded: 'Inventory system',
    timeline: 'Flexible',
    status: 'new',
    tags: ['Manufacturing'],
    notes: 'Large factory, needs inventory tracking.',
    leadScore: 31,
    source: 'Referral',
    createdAt: new Date('2026-07-03'),
    updatedAt: new Date('2026-07-03'),
    userId: 'demo',
  },
  {
    id: '13',
    name: 'Kevin Lee',
    email: 'kevin@bluebridge.io',
    phone: '+1 (650) 555-0188',
    company: 'BlueBridge',
    budget: 2800,
    industry: 'Consulting',
    serviceNeeded: 'Portfolio website',
    timeline: 'Next month',
    status: 'new',
    tags: ['Consulting'],
    notes: 'Freelance consultant, small project.',
    leadScore: 14,
    source: 'Social',
    createdAt: new Date('2026-07-04'),
    updatedAt: new Date('2026-07-04'),
    userId: 'demo',
  },
  {
    id: '14',
    name: 'Emma Torres',
    email: 'emma@vivamedical.com',
    phone: '+1 (305) 555-0112',
    company: 'Viva Medical',
    budget: 6000,
    industry: 'Healthcare',
    serviceNeeded: 'Appointment booking',
    timeline: 'This week',
    status: 'contacted',
    tags: ['Medical'],
    notes: 'Dental clinic. Needs online booking.',
    leadScore: 28,
    source: 'Website',
    createdAt: new Date('2026-06-29'),
    updatedAt: new Date('2026-07-01'),
    userId: 'demo',
  },
  {
    id: '15',
    name: 'James Wilson',
    email: 'james@titanindustries.com',
    phone: '+1 (214) 555-0155',
    company: 'Titan Industries',
    budget: 25000,
    industry: 'Finance',
    serviceNeeded: 'Trading platform',
    timeline: 'This week',
    status: 'meeting',
    tags: ['Enterprise', 'Finance'],
    notes: 'CEO wants a demo next week.',
    leadScore: 50,
    source: 'Direct',
    createdAt: new Date('2026-07-01'),
    updatedAt: new Date('2026-07-03'),
    userId: 'demo',
  },
]
